name: Linters

on: pull_request

env:
  FORCE_COLOR: 1

jobs:
  rubocop:
    name: Rubocop
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-ruby@v1
        with:
          ruby-version: 2.6.5
      - name: Setup Rubocop
        run: |
          gem install --no-document rubocop:'~>1.8' # https://docs.rubocop.org/en/stable/installation/
          [ -f .rubocop.yml ] || wget https://github.com/FlowFintech/FlowBack/blob/release/.rubocop.yml
      - name: Rubocop Report
        run: rubocop --color
